/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Sala;
import Persistencia.SalaData;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jeremias
 */
public class crearSala extends javax.swing.JInternalFrame {

    /**
     * Creates new form modificarUsuario
     */
    public crearSala() throws SQLException {
        initComponents();
        tablaSalas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        comboEstado2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboEstado5 = new javax.swing.JComboBox<>();
        buscarDNI1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(40, 463, 130, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro de Sala", "3D", "Capacidad Max.", "Habilitada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 310, 620, 140);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Habilitada:");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(50, 190, 106, 24);

        jButton4.setBackground(new java.awt.Color(215, 0, 0));
        jButton4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton4);
        jButton4.setBounds(542, 463, 120, 30);

        comboEstado2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        comboEstado2.setSelectedIndex(-1);
        jDesktopPane1.add(comboEstado2);
        comboEstado2.setBounds(160, 130, 240, 22);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salas existentes:");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(40, 276, 100, 30);

        comboEstado5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        comboEstado5.setSelectedIndex(-1);
        comboEstado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstado5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(comboEstado5);
        comboEstado5.setBounds(160, 190, 240, 22);
        jDesktopPane1.add(buscarDNI1);
        buscarDNI1.setBounds(160, 160, 240, 22);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Crear Sala");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(280, 20, 170, 50);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Es 3D:");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(50, 130, 106, 24);

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Capacidad:");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(50, 160, 106, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Proyeccion200-112.jpg"))); // NOI18N
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(420, 110, 200, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean test = false;
        while (comboEstado2.getSelectedIndex() != -1 && comboEstado5.getSelectedIndex() != -1 && buscarDNI1.getText().equals("")) {
            int apta3D = comboEstado2.getSelectedIndex();
            boolean isApta3D = true;

            int capacidad = Integer.parseInt(buscarDNI1.getText());

            int estado = comboEstado5.getSelectedIndex();
            boolean isEstado = true;

            switch (apta3D) {
                case 0:
                    isApta3D = true;
                    break;
                case 1:
                    isApta3D = false;
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "No eligió si la sala es apta para reproducir películas 3D o no.");
            }

            switch (estado) {
                case 0:
                    isEstado = true;
                    break;
                case 1:
                    isEstado = false;
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "No eligió si la sala está habilitada o no.");
                    break;
            }

            // boolean apta3D, int capacidad, boolean estado
            Sala nuevaSala = new Sala(isApta3D, capacidad, isEstado);
            SalaData sd = null;
            try {
                sd = new SalaData();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo acceder a la base de datos.");
            }

            sd.crearSala(nuevaSala);

            try {
                tablaSalas();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "No se pudo acceder a la base de datos.");
            }

            // limpiamos todos los campos luego de crear la sala
            buscarDNI1.setText("");
            comboEstado2.setSelectedIndex(-1);
            comboEstado5.setSelectedIndex(-1);
            test = true;
        }
        if (!test) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void comboEstado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstado5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEstado5ActionPerformed

    public void tablaSalas() throws SQLException {
        List<Sala> salas = new SalaData().listarSalas();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("nroSala");
        modelo.addColumn("es3D");
        modelo.addColumn("capacidad");
        modelo.addColumn("estado");

        for (Sala s : salas) {
            modelo.addRow(new Object[]{
                s.getNroSala(), s.isApta3D(), s.getCapacidad(), s.isEstado()
            });
        }

        jTable1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarDNI1;
    private javax.swing.JComboBox<String> comboEstado2;
    private javax.swing.JComboBox<String> comboEstado5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
