package Vista;

import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Grupo 11
 */
public class modificarPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form modificarUsuario
     */
    public modificarPelicula() throws SQLException {
        initComponents();
        tablaPeliculas();
        estreno_JDC.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        titulo_JTF = new javax.swing.JTextField();
        director_JTF = new javax.swing.JTextField();
        enCartelera_JCB = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        actores_JTF = new javax.swing.JTextField();
        origen_JTF = new javax.swing.JTextField();
        estreno_JDC = new com.toedter.calendar.JDateChooser();
        GeneroComboX = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Director", "Actores", "Origen", "Género", "Estreno", "En cartelera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 610, 156));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("En cartelera:");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 24));
        jDesktopPane1.add(titulo_JTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 227, -1));
        jDesktopPane1.add(director_JTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 227, -1));

        enCartelera_JCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jDesktopPane1.add(enCartelera_JCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 227, -1));

        jButton4.setBackground(new java.awt.Color(215, 0, 0));
        jButton4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 140, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modificar Pelicula");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 220, 50));
        jDesktopPane1.add(actores_JTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 227, -1));
        jDesktopPane1.add(origen_JTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 227, -1));
        jDesktopPane1.add(estreno_JDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 227, -1));

        GeneroComboX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil", "Terror", "Comedia", "Drama", "Suspenso", "Acción" }));
        GeneroComboX.setToolTipText("");
        GeneroComboX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroComboXActionPerformed(evt);
            }
        });
        jDesktopPane1.add(GeneroComboX, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 227, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Título:");
        jDesktopPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 106, 24));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Director:");
        jDesktopPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 24));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Actores:");
        jDesktopPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 24));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Orígen:");
        jDesktopPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 24));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Género:");
        jDesktopPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 110, 24));

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Estreno:");
        jDesktopPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, 24));

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Películas:");
        jDesktopPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, 24));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/crear_pelicula200-200.png"))); // NOI18N
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!titulo_JTF.getText().isEmpty() && !director_JTF.getText().equals("") && !actores_JTF.getText().isEmpty() && !origen_JTF.getText().isEmpty()
                &&  GeneroComboX.getSelectedIndex() != -1 && enCartelera_JCB.getSelectedIndex() != -1) {

            int fila = -1;
            fila = jTable1.getSelectedRow();

            String titulo = titulo_JTF.getText();
            String director = director_JTF.getText();
            String actores = actores_JTF.getText();
            String origen = origen_JTF.getText();
             int genero = GeneroComboX.getSelectedIndex();
            String generoSt = "";

            switch (genero) {
                case 0:
                    generoSt = "Infantil";
                    break;
                case 1:
                    generoSt = "Terror";
                    break;
                case 2:
                    generoSt = "Comedia";
                    break;
                case 3:
                    generoSt = "Drama";
                    break;
                case 4:
                    generoSt = "Suspenso";
                    break;
                case 5:
                    generoSt = "Acción";
                    break;
            }

            Boolean enCarteleraST = true;
            int enCartelera = -1;
            enCartelera = enCartelera_JCB.getSelectedIndex();

            Date estreno = new Date();
            try {
                estreno = estreno_JDC.getDate();
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "No puede no seleccionar una fecha.");
            }

            switch (enCartelera) {
                case 0:
                    enCarteleraST = true;
                    break;
                case 1:
                    enCarteleraST = false;
                    break;
            }

            if (fila != -1) {

                PeliculaData pd = null;
                Pelicula p = new Pelicula();

                int idPelicula = (Integer) jTable1.getValueAt(fila, 0);
                p.setIdPelicula(idPelicula);

                try {
                    pd = new PeliculaData();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al acceder a la base de datos.");
                }

                pd.modificarPelicula(p, titulo, director, actores, origen, generoSt, estreno, enCarteleraST);

                try {
                    tablaPeliculas();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error al acceder a la tabla.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe seleccionar una película.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        
        titulo_JTF.setText((String) jTable1.getValueAt(fila, 1));
        director_JTF.setText((String) jTable1.getValueAt(fila, 2));
        actores_JTF.setText((String) jTable1.getValueAt(fila, 3));
        origen_JTF.setText((String) jTable1.getValueAt(fila, 4));
        String generito = (String)jTable1.getValueAt(fila, 5);
        
        switch (generito) { //Infantil, Terror, Comedia, Drama, Suspenso, Acción
                case "Infantil":
                    GeneroComboX.setSelectedIndex(0);
                    break;
                case "Terror":
                    GeneroComboX.setSelectedIndex(1);
                    break;
                case "Comedia":
                    GeneroComboX.setSelectedIndex(2);
                    break;
                case "Drama":
                    GeneroComboX.setSelectedIndex(3);
                    break;
                case "Suspenso":
                    GeneroComboX.setSelectedIndex(4);
                    break;
                case "Acción":
                    GeneroComboX.setSelectedIndex(5);
                    break;
            }
        estreno_JDC.setDate((Date) jTable1.getValueAt(fila, 6));
        Boolean enCarteleraST = (Boolean) jTable1.getValueAt(fila, 7);

        if (enCarteleraST) {
            enCartelera_JCB.setSelectedIndex(0);
        } else {
            enCartelera_JCB.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void GeneroComboXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroComboXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroComboXActionPerformed

    public void tablaPeliculas() throws SQLException {
        List<Pelicula> pelis = new PeliculaData().listarPeliculas();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Director");
        modelo.addColumn("Actores");
        modelo.addColumn("Origen");
        modelo.addColumn("Genero");
        modelo.addColumn("Estreno");
        modelo.addColumn("En cartelera");

        for (Pelicula p : pelis) {
            modelo.addRow(new Object[]{
                p.getIdPelicula(), p.getTitulo(), p.getDirector(), p.getActores(), p.getOrigen(), p.getGenero(), p.getEstreno(), p.isEnCartelera()
            });
        }
        jTable1.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GeneroComboX;
    private javax.swing.JTextField actores_JTF;
    private javax.swing.JTextField director_JTF;
    private javax.swing.JComboBox<String> enCartelera_JCB;
    private com.toedter.calendar.JDateChooser estreno_JDC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField origen_JTF;
    private javax.swing.JTextField titulo_JTF;
    // End of variables declaration//GEN-END:variables
}
